import { app } from 'electron'
import { chmodSync, existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { paths } from '../core/paths.js'

/** Where Harbor always puts the command, with no privilege required. */
export function cliPath(): string {
  return join(paths.bin, 'harbor')
}

/** The conventional place to link it, which does require privilege. */
export const CLI_LINK = '/usr/local/bin/harbor'

/** The bundled CLI, packaged or in the source tree. */
function bundledCli(): string | null {
  for (const candidate of [
    join(process.resourcesPath, 'app.asar', 'out', 'cli', 'harbor.js'),
    join(app.getAppPath(), 'out', 'cli', 'harbor.js'),
    join(__dirname, '../../cli/harbor.js')
  ]) {
    if (existsSync(candidate)) return candidate
  }
  return null
}

/**
 * Write `~/.harbor/bin/harbor`.
 *
 * A shell script rather than a JavaScript file with a shebang, because the
 * machine may have no `node` at all — Harbor ships its own runtimes and does
 * not require one. Electron is a Node build, and `ELECTRON_RUN_AS_NODE` makes
 * the app's own binary run a script as plain Node, so the command works on a
 * machine with nothing else installed.
 *
 * Rewritten on every launch: the path to the app changes when it is moved or
 * updated, and a launcher pointing at where the app used to be is worse than
 * none — it fails with a stack trace instead of a sentence.
 */
export function installCli(): { path: string; ok: boolean; detail: string } {
  const target = cliPath()
  const script = bundledCli()
  if (!script) {
    return { path: target, ok: false, detail: 'the bundled CLI was not found in this build' }
  }

  const launcher = [
    '#!/bin/sh',
    '# Generated by Harbor. Rewritten on every launch; edits will be lost.',
    `exec env ELECTRON_RUN_AS_NODE=1 ${JSON.stringify(process.execPath)} ${JSON.stringify(script)} "$@"`,
    ''
  ].join('\n')

  try {
    mkdirSync(paths.bin, { recursive: true })
    // Only write when it changed, so an editor watching the directory is not
    // woken on every launch.
    if (!existsSync(target) || readFileSync(target, 'utf8') !== launcher) {
      writeFileSync(target, launcher, 'utf8')
    }
    chmodSync(target, 0o755)
    return { path: target, ok: true, detail: target }
  } catch (err) {
    return { path: target, ok: false, detail: (err as Error).message }
  }
}

/**
 * Link the command onto PATH.
 *
 * `/usr/local/bin` is root-owned on a stock Mac, so this asks for a password —
 * which is the right cost here: the user pressed a button asking for exactly
 * this. Harbor never does it on its own; writing to a directory outside
 * `~/.harbor` without being asked is not something an app should decide.
 */
export async function linkCli(privileged: {
  run(command: string): Promise<unknown>
}): Promise<void> {
  const target = cliPath()
  if (!existsSync(target)) throw new Error('The CLI is not installed yet')
  await privileged.run(`mkdir -p /usr/local/bin && ln -sf ${JSON.stringify(target)} ${CLI_LINK}`)
}

export async function unlinkCli(privileged: {
  run(command: string): Promise<unknown>
}): Promise<void> {
  await privileged.run(`rm -f ${CLI_LINK}`)
}

/** Whether the command is reachable as `harbor`, and from where. */
export function cliStatus(): {
  installed: boolean
  path: string
  linked: boolean
  linkPath: string
  onPath: boolean
} {
  const target = cliPath()
  const dirs = (process.env.PATH ?? '').split(':')
  return {
    installed: existsSync(target),
    path: target,
    linked: existsSync(CLI_LINK),
    linkPath: CLI_LINK,
    onPath: dirs.includes(paths.bin) || existsSync(CLI_LINK)
  }
}
