import { execFile as execFileCb } from 'node:child_process'
import { promisify } from 'node:util'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { NativeBackend } from '../backends/native-backend.js'
import type { PrivilegedHelper } from '../core/privileged-helper.js'
import type { ProcessManager } from '../core/process-manager.js'
import { paths } from '../core/paths.js'

const execFile = promisify(execFileCb)

/**
 * Both halves are needed: dscacheutil clears the DirectoryService cache, and
 * only a SIGHUP to mDNSResponder clears the one that actually holds the stale
 * negative answers.
 */
const FLUSH_COMMANDS = ['dscacheutil -flushcache', 'killall -HUP mDNSResponder']

/**
 * `*.<tld>` → 127.0.0.1.
 *
 * dnsmasq runs **unprivileged on a high port** rather than as root on 53: the
 * macOS resolver file can name a port, so binding 53 buys nothing and would
 * force the whole DNS subsystem to run as root. That leaves exactly one
 * privileged action — writing `/etc/resolver/<tld>` — so the user sees a single
 * password prompt for DNS, ever.
 *
 * Running it through ProcessManager (rather than `brew services`) means its
 * lifecycle and its logs come for free, like any other managed process.
 */
export class DnsmasqManager {
  /** Unprivileged: anything above 1024 works, and the resolver file names it. */
  readonly port = 5300

  constructor(
    private readonly native: NativeBackend,
    private readonly privileged: PrivilegedHelper,
    private readonly processes: ProcessManager
  ) {}

  private get configDir(): string {
    return join(paths.home, 'dnsmasq')
  }

  configPath(): string {
    return join(this.configDir, 'harbor.conf')
  }

  resolverPath(tld: string): string {
    return `/etc/resolver/${tld}`
  }

  isInstalled(): boolean {
    return this.native.which('dnsmasq') !== null
  }

  async install(): Promise<void> {
    await this.native.brewInstall('dnsmasq')
  }

  /** Our own config file — we never touch the user's dnsmasq.conf. */
  writeConfig(tld: string): string {
    mkdirSync(this.configDir, { recursive: true })
    const path = this.configPath()
    writeFileSync(
      path,
      [
        '# Generated by Harbor — do not edit by hand.',
        `port=${this.port}`,
        'listen-address=127.0.0.1',
        'bind-interfaces',
        // Only ever answer for our TLD; everything else stays with the system
        // resolver, which never routes those queries here anyway.
        'no-resolv',
        `address=/${tld}/127.0.0.1`,
        ''
      ].join('\n'),
      'utf8'
    )
    return path
  }

  isRunning(): boolean {
    return this.processes.findByOwner('system', 'dnsmasq') !== null
  }

  /**
   * PIDs of dnsmasq processes running against Harbor's own config file —
   * including ones this instance did not spawn, which is the normal state
   * after the app is relaunched or a script bows out. They must be stopped
   * before a new pool can bind the port, and matching on our config path means
   * this can never touch the user's own dnsmasq.
   */
  private async harborDnsmasqPids(): Promise<number[]> {
    const config = this.configPath()
    try {
      const { stdout } = await execFile('/bin/ps', ['-Ao', 'pid=,args='])
      return stdout
        .split('\n')
        .filter((l) => l.includes('dnsmasq') && l.includes(config))
        .map((l) => Number(l.trim().split(/\s+/)[0]))
        .filter((pid) => Number.isFinite(pid) && pid !== process.pid)
    } catch {
      return []
    }
  }

  async start(tld: string): Promise<void> {
    const binary = this.native.which('dnsmasq')
    if (!binary) throw new Error('dnsmasq is not installed — install it with: brew install dnsmasq')
    if (this.isRunning()) await this.stop()

    // Also clear any Harbor dnsmasq this instance did not spawn; otherwise the
    // new one silently loses the race for the port and never answers.
    for (const pid of await this.harborDnsmasqPids()) {
      try {
        process.kill(pid, 'SIGTERM')
      } catch {
        /* already gone */
      }
    }
    await new Promise((r) => setTimeout(r, 300))

    const config = this.writeConfig(tld)
    await this.processes.spawn({
      owner: { kind: 'system', id: 'dnsmasq' },
      label: 'dnsmasq',
      command: binary,
      // -k keeps it in the foreground so ProcessManager owns the lifecycle;
      // logging to stderr routes it into the aggregator.
      args: ['-k', '-C', config, '--log-facility=-']
    })

    // A spawned process is not yet a listening one. Returning before the
    // socket is bound makes the very next query fail for no real reason.
    // Cheap, needs no password, and covers the common case of a name that was
    // looked up moments before dnsmasq came up.
    await this.flushDnsCacheUnprivileged()

    if (!(await this.waitUntilResolving(tld))) {
      // Almost always something else already on the port — most often a
      // dnsmasq orphaned by a previous Harbor that was force-quit.
      const holder = await this.portHolder()
      throw new Error(
        `dnsmasq did not answer for *.${tld}` +
          (holder ? ` — port ${this.port} is held by ${holder}` : '')
      )
    }
  }

  /** Poll until dnsmasq answers our probe, or give up. */
  async waitUntilResolving(tld: string, timeoutMs = 5000): Promise<boolean> {
    const deadline = Date.now() + timeoutMs
    while (Date.now() < deadline) {
      if ((await this.answers(`harbor-probe.${tld}`)) === '127.0.0.1') return true
      await new Promise((r) => setTimeout(r, 150))
    }
    return false
  }

  async stop(): Promise<void> {
    const handle = this.processes.findByOwner('system', 'dnsmasq')
    if (handle) await this.processes.stop(handle.id)
  }

  resolverConfigured(tld: string): boolean {
    return existsSync(this.resolverPath(tld))
  }

  /**
   * The one privileged step. Writes /etc/resolver/<tld> and flushes the DNS
   * cache in a single prompt.
   *
   * The flush is not optional. macOS caches negative lookups in mDNSResponder,
   * and `dscacheutil -flushcache` alone no longer clears them — so a name that
   * was queried before Harbor owned the suffix stays unresolvable, with the
   * resolver file correct and dnsmasq answering that exact name when asked
   * directly. It looks like a DNS bug and is a stale cache.
   */
  async configureResolver(tld: string): Promise<void> {
    await this.privileged.runAll([
      'mkdir -p /etc/resolver',
      `printf 'nameserver 127.0.0.1\\nport ${this.port}\\n' > ${this.resolverPath(tld)}`,
      ...FLUSH_COMMANDS
    ])
  }

  /** Clear the macOS resolver caches. Needs root for the mDNSResponder half. */
  async flushDnsCache(): Promise<void> {
    await this.privileged.runAll(FLUSH_COMMANDS)
  }

  /** The half that needs no password, for use after an ordinary restart. */
  async flushDnsCacheUnprivileged(): Promise<void> {
    await execFile('/usr/bin/dscacheutil', ['-flushcache']).catch(() => undefined)
  }

  async removeResolver(tld: string): Promise<void> {
    await this.privileged.removeFile(this.resolverPath(tld))
  }

  /** What already occupies our port, for a failure message worth reading. */
  private async portHolder(): Promise<string | null> {
    try {
      const { stdout } = await execFile('/usr/sbin/lsof', [
        '-nP',
        `-iUDP:${this.port}`,
        '-Fcp'
      ])
      const pid = /^p(\d+)/m.exec(stdout)?.[1]
      const command = /^c(.+)$/m.exec(stdout)?.[1]
      return pid && command ? `${command} (pid ${pid})` : null
    } catch {
      return null
    }
  }

  /** Ask our own dnsmasq directly — proves the config without needing /etc. */
  async answers(name: string): Promise<string | null> {
    try {
      const { stdout } = await execFile('/usr/bin/dig', [
        '@127.0.0.1',
        '-p',
        String(this.port),
        '+short',
        '+time=2',
        '+tries=1',
        name
      ])
      const first = stdout.trim().split('\n')[0]
      return first || null
    } catch {
      return null
    }
  }

  async status(tld: string): Promise<{
    installed: boolean
    running: boolean
    resolverConfigured: boolean
    port: number
    resolves: boolean
  }> {
    const installed = this.isInstalled()
    const running = this.isRunning()
    return {
      installed,
      running,
      resolverConfigured: this.resolverConfigured(tld),
      port: this.port,
      resolves: running ? (await this.answers(`harbor-probe.${tld}`)) === '127.0.0.1' : false
    }
  }
}
