import { execFile as execFileCb } from 'node:child_process'
import { promisify } from 'node:util'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { NativeBackend } from '../backends/native-backend.js'
import type { PrivilegedHelper } from '../core/privileged-helper.js'
import type { ProcessManager } from '../core/process-manager.js'
import { paths } from '../core/paths.js'

const execFile = promisify(execFileCb)

/**
 * `*.<tld>` → 127.0.0.1.
 *
 * dnsmasq runs **unprivileged on a high port** rather than as root on 53: the
 * macOS resolver file can name a port, so binding 53 buys nothing and would
 * force the whole DNS subsystem to run as root. That leaves exactly one
 * privileged action — writing `/etc/resolver/<tld>` — so the user sees a single
 * password prompt for DNS, ever.
 *
 * Running it through ProcessManager (rather than `brew services`) means its
 * lifecycle and its logs come for free, like any other managed process.
 */
export class DnsmasqManager {
  /** Unprivileged: anything above 1024 works, and the resolver file names it. */
  readonly port = 5300

  constructor(
    private readonly native: NativeBackend,
    private readonly privileged: PrivilegedHelper,
    private readonly processes: ProcessManager
  ) {}

  private get configDir(): string {
    return join(paths.home, 'dnsmasq')
  }

  configPath(): string {
    return join(this.configDir, 'harbor.conf')
  }

  resolverPath(tld: string): string {
    return `/etc/resolver/${tld}`
  }

  isInstalled(): boolean {
    return this.native.which('dnsmasq') !== null
  }

  async install(): Promise<void> {
    await this.native.brewInstall('dnsmasq')
  }

  /** Our own config file — we never touch the user's dnsmasq.conf. */
  writeConfig(tld: string): string {
    mkdirSync(this.configDir, { recursive: true })
    const path = this.configPath()
    writeFileSync(
      path,
      [
        '# Generated by Harbor — do not edit by hand.',
        `port=${this.port}`,
        'listen-address=127.0.0.1',
        'bind-interfaces',
        // Only ever answer for our TLD; everything else stays with the system
        // resolver, which never routes those queries here anyway.
        'no-resolv',
        `address=/${tld}/127.0.0.1`,
        ''
      ].join('\n'),
      'utf8'
    )
    return path
  }

  isRunning(): boolean {
    return this.processes.findByOwner('system', 'dnsmasq') !== null
  }

  async start(tld: string): Promise<void> {
    const binary = this.native.which('dnsmasq')
    if (!binary) throw new Error('dnsmasq is not installed — install it with: brew install dnsmasq')
    if (this.isRunning()) await this.stop()

    const config = this.writeConfig(tld)
    await this.processes.spawn({
      owner: { kind: 'system', id: 'dnsmasq' },
      label: 'dnsmasq',
      command: binary,
      // -k keeps it in the foreground so ProcessManager owns the lifecycle;
      // logging to stderr routes it into the aggregator.
      args: ['-k', '-C', config, '--log-facility=-']
    })

    // A spawned process is not yet a listening one. Returning before the
    // socket is bound makes the very next query fail for no real reason.
    if (!(await this.waitUntilResolving(tld))) {
      throw new Error(`dnsmasq started but did not answer for *.${tld}`)
    }
  }

  /** Poll until dnsmasq answers our probe, or give up. */
  async waitUntilResolving(tld: string, timeoutMs = 5000): Promise<boolean> {
    const deadline = Date.now() + timeoutMs
    while (Date.now() < deadline) {
      if ((await this.answers(`harbor-probe.${tld}`)) === '127.0.0.1') return true
      await new Promise((r) => setTimeout(r, 150))
    }
    return false
  }

  async stop(): Promise<void> {
    const handle = this.processes.findByOwner('system', 'dnsmasq')
    if (handle) await this.processes.stop(handle.id)
  }

  resolverConfigured(tld: string): boolean {
    return existsSync(this.resolverPath(tld))
  }

  /** The one privileged step. Writes /etc/resolver/<tld> in a single prompt. */
  async configureResolver(tld: string): Promise<void> {
    await this.privileged.runAll([
      'mkdir -p /etc/resolver',
      `printf 'nameserver 127.0.0.1\\nport ${this.port}\\n' > ${this.resolverPath(tld)}`
    ])
  }

  async removeResolver(tld: string): Promise<void> {
    await this.privileged.removeFile(this.resolverPath(tld))
  }

  /** Ask our own dnsmasq directly — proves the config without needing /etc. */
  async answers(name: string): Promise<string | null> {
    try {
      const { stdout } = await execFile('/usr/bin/dig', [
        '@127.0.0.1',
        '-p',
        String(this.port),
        '+short',
        '+time=2',
        '+tries=1',
        name
      ])
      const first = stdout.trim().split('\n')[0]
      return first || null
    } catch {
      return null
    }
  }

  async status(tld: string): Promise<{
    installed: boolean
    running: boolean
    resolverConfigured: boolean
    port: number
    resolves: boolean
  }> {
    const installed = this.isInstalled()
    const running = this.isRunning()
    return {
      installed,
      running,
      resolverConfigured: this.resolverConfigured(tld),
      port: this.port,
      resolves: running ? (await this.answers(`harbor-probe.${tld}`)) === '127.0.0.1' : false
    }
  }
}
