import { existsSync, mkdirSync, writeFileSync, rmSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { exec as execCb } from 'node:child_process'
import { promisify } from 'node:util'
import type { NginxRewriteRule, Project } from '../../shared/project.js'
import type { NativeBackend } from '../backends/native-backend.js'
import type { PrivilegedHelper } from '../core/privileged-helper.js'
import { paths } from '../core/paths.js'

const exec = promisify(execCb)

export interface VhostContext {
  project: Project
  /** Absolute docroot. For fpm/static this is what nginx serves from. */
  root: string
  /** fpm only: the PHP-FPM socket to fastcgi_pass to. */
  fpmSocket?: string
  /** fpm only: front controller filename from the framework driver. */
  frontController?: string
  /** fpm/static: extra location blocks from the framework driver. */
  rewrites?: NginxRewriteRule[]
  /** reverse-proxy only: the allocated upstream port. */
  proxyPort?: number
  /** TLS cert paths when the site is secured. */
  cert?: { certFile: string; keyFile: string }
}

/**
 * Nginx is the single front door for every `.test` domain regardless of serve
 * model — only what sits behind it changes. All three models render from this
 * one file; there are no per-project-type nginx branches anywhere else.
 */
export class NginxManager {
  constructor(
    private readonly native: NativeBackend,
    private readonly privileged: PrivilegedHelper
  ) {}

  vhostPath(project: Project): string {
    return join(paths.vhosts, `${project.domain}.conf`)
  }

  ensureRootConfig(): void {
    mkdirSync(paths.vhosts, { recursive: true })
    const main = join(paths.nginx, 'harbor.conf')
    if (!existsSync(main)) {
      writeFileSync(main, `include ${paths.vhosts}/*.conf;\n`, 'utf8')
    }
  }

  write(ctx: VhostContext): string {
    this.ensureRootConfig()
    const path = this.vhostPath(ctx.project)
    writeFileSync(path, this.render(ctx), 'utf8')
    return path
  }

  remove(project: Project): void {
    rmSync(this.vhostPath(project), { force: true })
  }

  render(ctx: VhostContext): string {
    const { project } = ctx
    const listen = ctx.cert
      ? ['listen 443 ssl;', 'listen [::]:443 ssl;', 'http2 on;']
      : ['listen 80;', 'listen [::]:80;']

    const tls = ctx.cert
      ? [`ssl_certificate ${ctx.cert.certFile};`, `ssl_certificate_key ${ctx.cert.keyFile};`]
      : []

    const body =
      project.serveModel === 'reverse-proxy'
        ? this.reverseProxyBody(ctx)
        : project.serveModel === 'fpm'
          ? this.fpmBody(ctx)
          : this.staticBody(ctx)

    return [
      `# Generated by Harbor for ${project.name} — do not edit by hand.`,
      'server {',
      indent([
        ...listen,
        `server_name ${project.domain};`,
        ...tls,
        `access_log ${join(paths.logs, `${project.domain}.access.log`)};`,
        `error_log ${join(paths.logs, `${project.domain}.error.log`)};`,
        'charset utf-8;',
        'client_max_body_size 512M;',
        ...body
      ]),
      '}',
      ''
    ].join('\n')
  }

  private reverseProxyBody(ctx: VhostContext): string[] {
    if (!ctx.proxyPort) throw new Error(`${ctx.project.name}: reverse-proxy vhost needs a port`)
    return [
      'location / {',
      ...indent([
        `proxy_pass http://127.0.0.1:${ctx.proxyPort};`,
        'proxy_http_version 1.1;',
        'proxy_set_header Upgrade $http_upgrade;',
        "proxy_set_header Connection 'upgrade';",
        'proxy_set_header Host $host;',
        'proxy_set_header X-Real-IP $remote_addr;',
        'proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
        'proxy_set_header X-Forwarded-Proto $scheme;',
        'proxy_cache_bypass $http_upgrade;',
        // Dev servers hold long-lived HMR sockets open.
        'proxy_read_timeout 3600s;'
      ]),
      '}'
    ]
  }

  private fpmBody(ctx: VhostContext): string[] {
    if (!ctx.fpmSocket) throw new Error(`${ctx.project.name}: fpm vhost needs a socket path`)
    const front = ctx.frontController ?? 'index.php'
    return [
      `root ${ctx.root};`,
      `index ${front};`,
      ...this.rewriteBlocks(ctx.rewrites),
      '',
      'location ~ \\.php$ {',
      ...indent([
        'include fastcgi_params;',
        `fastcgi_pass unix:${ctx.fpmSocket};`,
        'fastcgi_index index.php;',
        'fastcgi_split_path_info ^(.+\\.php)(/.+)$;',
        'fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;',
        'fastcgi_param PATH_INFO $fastcgi_path_info;',
        'fastcgi_param HTTPS $https if_not_empty;',
        'fastcgi_buffers 16 16k;',
        'fastcgi_buffer_size 32k;',
        'fastcgi_read_timeout 600;'
      ]),
      '}',
      '',
      'location ~ /\\.(?!well-known).* {',
      ...indent(['deny all;']),
      '}'
    ]
  }

  private staticBody(ctx: VhostContext): string[] {
    return [
      `root ${ctx.root};`,
      'index index.html index.htm;',
      ...this.rewriteBlocks(
        ctx.rewrites ?? [{ location: '/', directives: ['try_files $uri $uri/ /index.html;'] }]
      )
    ]
  }

  private rewriteBlocks(rules: NginxRewriteRule[] | undefined): string[] {
    if (!rules?.length) return []
    return rules.flatMap((rule) => [
      `location ${rule.location} {`,
      ...indent(rule.directives),
      '}'
    ])
  }

  // ── front door connection ───────────────────────────────────────────────
  //
  // Rendering a vhost into ~/.harbor is not enough: the system nginx has to be
  // told to read it. Without the include below, every vhost Harbor generates
  // is inert. This is the one edit Harbor makes to a file it does not own, so
  // it is idempotent, backed up once, and reversible.

  harborConfigPath(): string {
    return join(paths.nginx, 'harbor.conf')
  }

  private includeLine(): string {
    return `include ${this.harborConfigPath()};`
  }

  /** Where the system nginx reads its config from. */
  systemConfigPath(): string | null {
    const prefix = this.native.brewPrefix()
    if (!prefix) return null
    const candidate = join(prefix, 'etc', 'nginx', 'nginx.conf')
    return existsSync(candidate) ? candidate : null
  }

  private backupPath(): string {
    return join(paths.nginx, 'nginx.conf.pre-harbor')
  }

  isConnected(): boolean {
    const config = this.systemConfigPath()
    if (!config) return false
    try {
      return readFileSync(config, 'utf8').includes(this.includeLine())
    } catch {
      return false
    }
  }

  /** Add the include and reload. Prompts for root once. */
  async connect(): Promise<void> {
    const config = this.systemConfigPath()
    if (!config) throw new Error('nginx is not installed — install it with: brew install nginx')

    this.ensureRootConfig()
    const next = insertHarborInclude(readFileSync(config, 'utf8'), this.includeLine())
    if (next === null) return // already connected

    const staged = join(paths.nginx, 'nginx.conf.staged')
    writeFileSync(staged, next, 'utf8')
    await this.privileged.installFile(staged, config, this.backupPath())
    rmSync(staged, { force: true })

    const check = await this.test()
    if (!check.ok) {
      // Put the original back rather than leaving nginx unable to start.
      await this.privileged.installFile(this.backupPath(), config)
      throw new Error(`nginx rejected the config, reverted: ${check.output}`)
    }
    await this.reload()
  }

  async disconnect(): Promise<void> {
    const config = this.systemConfigPath()
    if (!config) return
    const next = removeHarborInclude(readFileSync(config, 'utf8'), this.includeLine())
    if (next === null) return

    const staged = join(paths.nginx, 'nginx.conf.staged')
    writeFileSync(staged, next, 'utf8')
    await this.privileged.installFile(staged, config)
    rmSync(staged, { force: true })
    await this.reload()
  }

  async status(): Promise<{
    installed: boolean
    running: boolean
    connected: boolean
    configPath: string | null
    harborConfig: string
  }> {
    const binary = this.native.which('nginx')
    const harborConfig = this.harborConfigPath()
    if (!binary) {
      return { installed: false, running: false, connected: false, configPath: null, harborConfig }
    }
    const running = await exec('/usr/bin/pgrep -x nginx')
      .then(() => true)
      .catch(() => false)
    return {
      installed: true,
      running,
      connected: this.isConnected(),
      configPath: this.systemConfigPath(),
      harborConfig
    }
  }

  /** Validate before reloading — a bad vhost must not take every site down. */
  async test(): Promise<{ ok: boolean; output: string }> {
    const binary = this.native.which('nginx')
    if (!binary) return { ok: false, output: 'nginx is not installed' }
    try {
      const { stderr } = await exec(`${binary} -t`)
      return { ok: true, output: stderr }
    } catch (err) {
      return { ok: false, output: (err as Error).message }
    }
  }

  /** Reload goes through PrivilegedHelper: nginx binds 80/443, so it needs root. */
  async reload(): Promise<void> {
    const check = await this.test()
    if (!check.ok) throw new Error(`nginx config test failed: ${check.output}`)
    const binary = this.native.which('nginx')
    await this.privileged.run(`${binary} -s reload`)
  }

  /** Read back a rendered vhost — used by the UI's "show config" affordance. */
  read(project: Project): string | null {
    const path = this.vhostPath(project)
    return existsSync(path) ? readFileSync(path, 'utf8') : null
  }
}

export const HARBOR_MARKER = '# Added by Harbor'

/**
 * Insert Harbor's include as the first directive inside the top-level `http {}`
 * block. Returns null when it is already present, so callers can treat a
 * repeat connect as a no-op rather than duplicating the line.
 */
export function insertHarborInclude(source: string, includeLine: string): string | null {
  if (source.includes(includeLine)) return null

  const lines = source.split('\n')
  // Match only a top-level `http {`, not a `server {` nested inside one.
  const httpIndex = lines.findIndex((line) => /^\s*http\s*\{/.test(line))
  if (httpIndex === -1) throw new Error('No top-level http { } block found in nginx.conf')

  lines.splice(
    httpIndex + 1,
    0,
    '',
    `    ${HARBOR_MARKER} — serves every .test vhost. Safe to remove.`,
    `    ${includeLine}`
  )
  return lines.join('\n')
}

/**
 * Reverse of insertHarborInclude, exactly: the blank spacer we inserted goes
 * too. A filter that only dropped the marker and include would leave one blank
 * line behind per cycle, slowly accreting in a file Harbor does not own.
 * Returns null when there is nothing to remove.
 */
export function removeHarborInclude(source: string, includeLine: string): string | null {
  if (!source.includes(includeLine)) return null

  const out: string[] = []
  for (const line of source.split('\n')) {
    if (line.includes(HARBOR_MARKER)) {
      // Drop our spacer, but never a blank the user's own config had there.
      if (out[out.length - 1]?.trim() === '') out.pop()
      continue
    }
    if (line.includes(includeLine)) continue
    out.push(line)
  }
  return out.join('\n')
}

function indent(lines: string[], depth = 1): string[] {
  const pad = '    '.repeat(depth)
  return lines.map((l) => (l ? `${pad}${l}` : l))
}
