import { existsSync, mkdirSync, writeFileSync, rmSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { exec as execCb } from 'node:child_process'
import { promisify } from 'node:util'
import type { NginxRewriteRule, Project } from '../../shared/project.js'
import type { NativeBackend } from '../backends/native-backend.js'
import type { PrivilegedHelper } from '../core/privileged-helper.js'
import { paths } from '../core/paths.js'

const exec = promisify(execCb)

export interface VhostContext {
  project: Project
  /** Absolute docroot. For fpm/static this is what nginx serves from. */
  root: string
  /** fpm only: the PHP-FPM socket to fastcgi_pass to. */
  fpmSocket?: string
  /** fpm only: front controller filename from the framework driver. */
  frontController?: string
  /** fpm/static: extra location blocks from the framework driver. */
  rewrites?: NginxRewriteRule[]
  /** reverse-proxy only: the allocated upstream port. */
  proxyPort?: number
  /** TLS cert paths when the site is secured. */
  cert?: { certFile: string; keyFile: string }
  /** Listen ports. Default to 80/443; overridable so Harbor can run unprivileged. */
  httpPort?: number
  httpsPort?: number
}

/**
 * Nginx is the single front door for every `.test` domain regardless of serve
 * model — only what sits behind it changes. All three models render from this
 * one file; there are no per-project-type nginx branches anywhere else.
 */
export class NginxManager {
  private runningCache: { value: boolean; at: number } | null = null

  constructor(
    private readonly native: NativeBackend,
    private readonly privileged: PrivilegedHelper
  ) {}

  vhostPath(project: Project): string {
    return join(paths.vhosts, `${project.domain}.conf`)
  }

  ensureRootConfig(): void {
    mkdirSync(paths.vhosts, { recursive: true })
    const main = join(paths.nginx, 'harbor.conf')
    if (!existsSync(main)) {
      writeFileSync(main, `include ${paths.vhosts}/*.conf;\n`, 'utf8')
    }
  }

  write(ctx: VhostContext): string {
    this.ensureRootConfig()
    const path = this.vhostPath(ctx.project)
    writeFileSync(path, this.render(ctx), 'utf8')
    return path
  }

  remove(project: Project): void {
    rmSync(this.vhostPath(project), { force: true })
  }

  render(ctx: VhostContext): string {
    const { project } = ctx
    const httpPort = ctx.httpPort ?? 80
    const httpsPort = ctx.httpsPort ?? 443
    const listen = ctx.cert
      ? [`listen ${httpsPort} ssl;`, `listen [::]:${httpsPort} ssl;`, 'http2 on;']
      : [`listen ${httpPort};`, `listen [::]:${httpPort};`]

    const tls = ctx.cert
      ? [`ssl_certificate ${ctx.cert.certFile};`, `ssl_certificate_key ${ctx.cert.keyFile};`]
      : []

    const body =
      project.serveModel === 'reverse-proxy'
        ? this.reverseProxyBody(ctx)
        : project.serveModel === 'fpm'
          ? this.fpmBody(ctx)
          : this.staticBody(ctx)

    // A secured site still has to answer on the HTTP port. Without this block
    // http://<site> falls through to whichever other vhost is the default
    // server for that port — serving someone else's project, or a 403.
    const redirect = ctx.cert
      ? [
          'server {',
          ...indent([
            `listen ${httpPort};`,
            `listen [::]:${httpPort};`,
            `server_name ${project.domain};`,
            `return 301 https://$host${httpsPort === 443 ? '' : `:${httpsPort}`}$request_uri;`
          ]),
          '}',
          ''
        ]
      : []

    return [
      `# Generated by Harbor for ${project.name} — do not edit by hand.`,
      ...redirect,
      'server {',
      // Spread, not nest: an array element inside the array would be stringified
      // by join() into one comma-separated line, producing a config that looks
      // plausible in a substring check and is rejected by nginx.
      ...indent([
        ...listen,
        `server_name ${project.domain};`,
        ...tls,
        `access_log ${join(paths.logs, `${project.domain}.access.log`)};`,
        `error_log ${join(paths.logs, `${project.domain}.error.log`)};`,
        'charset utf-8;',
        'client_max_body_size 512M;',
        ...body
      ]),
      '}',
      ''
    ].join('\n')
  }

  private reverseProxyBody(ctx: VhostContext): string[] {
    if (!ctx.proxyPort) throw new Error(`${ctx.project.name}: reverse-proxy vhost needs a port`)
    return [
      'location / {',
      ...indent([
        `proxy_pass http://127.0.0.1:${ctx.proxyPort};`,
        'proxy_http_version 1.1;',
        'proxy_set_header Upgrade $http_upgrade;',
        "proxy_set_header Connection 'upgrade';",
        'proxy_set_header Host $host;',
        'proxy_set_header X-Real-IP $remote_addr;',
        'proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
        'proxy_set_header X-Forwarded-Proto $scheme;',
        'proxy_cache_bypass $http_upgrade;',
        // Dev servers hold long-lived HMR sockets open.
        'proxy_read_timeout 3600s;'
      ]),
      '}'
    ]
  }

  private fpmBody(ctx: VhostContext): string[] {
    if (!ctx.fpmSocket) throw new Error(`${ctx.project.name}: fpm vhost needs a socket path`)
    const front = ctx.frontController ?? 'index.php'
    return [
      `root ${ctx.root};`,
      `index ${front};`,
      ...this.rewriteBlocks(ctx.rewrites),
      '',
      'location ~ \\.php$ {',
      ...indent([
        'include fastcgi_params;',
        `fastcgi_pass unix:${ctx.fpmSocket};`,
        'fastcgi_index index.php;',
        'fastcgi_split_path_info ^(.+\\.php)(/.+)$;',
        'fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;',
        'fastcgi_param PATH_INFO $fastcgi_path_info;',
        'fastcgi_param HTTPS $https if_not_empty;',
        'fastcgi_buffers 16 16k;',
        'fastcgi_buffer_size 32k;',
        'fastcgi_read_timeout 600;'
      ]),
      '}',
      '',
      'location ~ /\\.(?!well-known).* {',
      ...indent(['deny all;']),
      '}'
    ]
  }

  private staticBody(ctx: VhostContext): string[] {
    return [
      `root ${ctx.root};`,
      'index index.html index.htm;',
      ...this.rewriteBlocks(
        ctx.rewrites ?? [{ location: '/', directives: ['try_files $uri $uri/ /index.html;'] }]
      )
    ]
  }

  private rewriteBlocks(rules: NginxRewriteRule[] | undefined): string[] {
    if (!rules?.length) return []
    return rules.flatMap((rule) => [
      `location ${rule.location} {`,
      ...indent(rule.directives),
      '}'
    ])
  }

  // ── front door connection ───────────────────────────────────────────────
  //
  // Rendering a vhost into ~/.harbor is not enough: the system nginx has to be
  // told to read it. Without the include below, every vhost Harbor generates
  // is inert. This is the one edit Harbor makes to a file it does not own, so
  // it is idempotent, backed up once, and reversible.

  harborConfigPath(): string {
    return join(paths.nginx, 'harbor.conf')
  }

  private includeLine(): string {
    return `include ${this.harborConfigPath()};`
  }

  /**
   * Homebrew's nginx.conf ends with `include servers/*;` and that directory is
   * user-writable, so on a standard install Harbor can connect itself with a
   * drop-in file and never touch nginx.conf or ask for a password. Editing the
   * main config is the fallback for installs without that hook.
   */
  dropInPath(): string | null {
    const prefix = this.native.brewPrefix()
    if (!prefix) return null
    const dir = join(prefix, 'etc', 'nginx', 'servers')
    if (!existsSync(dir)) return null

    const config = this.systemConfigPath()
    if (!config) return null
    try {
      // Only usable if the main config actually reads that directory.
      if (!/include\s+servers\/\*/.test(readFileSync(config, 'utf8'))) return null
    } catch {
      return null
    }
    return join(dir, 'harbor.conf')
  }

  /** Where the system nginx reads its config from. */
  systemConfigPath(): string | null {
    const prefix = this.native.brewPrefix()
    if (!prefix) return null
    const candidate = join(prefix, 'etc', 'nginx', 'nginx.conf')
    return existsSync(candidate) ? candidate : null
  }

  private backupPath(): string {
    return join(paths.nginx, 'nginx.conf.pre-harbor')
  }

  isConnected(): boolean {
    const dropIn = this.dropInPath()
    if (dropIn && existsSync(dropIn)) {
      try {
        if (readFileSync(dropIn, 'utf8').includes(this.includeLine())) return true
      } catch {
        /* fall through to the main config */
      }
    }
    const config = this.systemConfigPath()
    if (!config) return false
    try {
      return readFileSync(config, 'utf8').includes(this.includeLine())
    } catch {
      return false
    }
  }

  /** Which mechanism connect() would use, for display and for tests. */
  strategy(): 'drop-in' | 'config-edit' | null {
    if (!this.native.which('nginx')) return null
    return this.dropInPath() ? 'drop-in' : this.systemConfigPath() ? 'config-edit' : null
  }

  /** Add the include and reload. Only prompts for root on the fallback path. */
  async connect(): Promise<void> {
    this.ensureRootConfig()

    const dropIn = this.dropInPath()
    if (dropIn) {
      writeFileSync(
        dropIn,
        `${HARBOR_MARKER} — serves every Harbor vhost. Safe to remove.\n${this.includeLine()}\n`,
        'utf8'
      )
      const dropInCheck = await this.test()
      if (!dropInCheck.ok) {
        rmSync(dropIn, { force: true })
        throw new Error(`nginx rejected the config, reverted: ${dropInCheck.output}`)
      }
      await this.reload()
      return
    }

    const config = this.systemConfigPath()
    if (!config) throw new Error('nginx is not installed — install it with: brew install nginx')
    const next = insertHarborInclude(readFileSync(config, 'utf8'), this.includeLine())
    if (next === null) return // already connected

    const staged = join(paths.nginx, 'nginx.conf.staged')
    writeFileSync(staged, next, 'utf8')
    await this.privileged.installFile(staged, config, this.backupPath())
    rmSync(staged, { force: true })

    const check = await this.test()
    if (!check.ok) {
      // Put the original back rather than leaving nginx unable to start.
      await this.privileged.installFile(this.backupPath(), config)
      throw new Error(`nginx rejected the config, reverted: ${check.output}`)
    }
    await this.reload()
  }

  async disconnect(): Promise<void> {
    const dropIn = this.dropInPath()
    if (dropIn && existsSync(dropIn)) {
      rmSync(dropIn, { force: true })
      await this.reload().catch(() => undefined)
      return
    }

    const config = this.systemConfigPath()
    if (!config) return
    const next = removeHarborInclude(readFileSync(config, 'utf8'), this.includeLine())
    if (next === null) return

    const staged = join(paths.nginx, 'nginx.conf.staged')
    writeFileSync(staged, next, 'utf8')
    await this.privileged.installFile(staged, config)
    rmSync(staged, { force: true })
    await this.reload()
  }

  /** The user the running master belongs to, or null when it isn't running. */
  private async masterUser(): Promise<string | null> {
    try {
      const { stdout } = await exec('/usr/bin/pgrep -x nginx')
      const pid = stdout.trim().split('\n')[0]
      if (!pid) return null
      const { stdout: owner } = await exec(`/bin/ps -o user= -p ${pid}`)
      return owner.trim() || null
    } catch {
      return null
    }
  }

  /**
   * Ports below 1024 can only be bound by root, so a site on :443 needs a root
   * master. Above that Harbor can run nginx as the user and never prompt.
   */
  private needsRoot(ports: number[]): boolean {
    return ports.some((p) => p < 1024)
  }

  async start(ports: { httpPort: number; httpsPort: number }): Promise<void> {
    const binary = this.native.which('nginx')
    if (!binary) throw new Error('nginx is not installed — install it with: brew install nginx')

    const check = await this.test()
    if (!check.ok) throw new Error(`nginx config test failed: ${check.output}`)

    if (this.needsRoot([ports.httpPort, ports.httpsPort])) {
      await this.privileged.run(binary)
    } else {
      await exec(binary)
    }
  }

  async stop(): Promise<void> {
    const binary = this.native.which('nginx')
    if (!binary) return
    const owner = await this.masterUser()
    if (!owner) return
    if (owner === 'root') await this.privileged.run(`${binary} -s stop`)
    else await exec(`${binary} -s stop`).catch(() => undefined)
    // Give the master a moment to release its listeners before a restart.
    await new Promise((r) => setTimeout(r, 600))
  }

  /**
   * A running master holds the listeners it was started with; a reload will not
   * move it from :8080 to :80. Changing ports means a full restart.
   */
  async restart(ports: { httpPort: number; httpsPort: number }): Promise<void> {
    await this.stop()
    await this.start(ports)
  }

  async status(): Promise<{
    installed: boolean
    running: boolean
    connected: boolean
    configPath: string | null
    harborConfig: string
    strategy: 'drop-in' | 'config-edit' | null
    /** The user the master runs as; root is required to bind 80/443. */
    runningAs: string | null
    /** Ports the running master is actually listening on. */
    listening: number[]
  }> {
    const binary = this.native.which('nginx')
    const harborConfig = this.harborConfigPath()
    if (!binary) {
      return {
        installed: false,
        running: false,
        connected: false,
        configPath: null,
        harborConfig,
        strategy: null,
        runningAs: null,
        listening: []
      }
    }
    const running = await exec('/usr/bin/pgrep -x nginx')
      .then(() => true)
      .catch(() => false)
    return {
      installed: true,
      running,
      connected: this.isConnected(),
      configPath: this.systemConfigPath(),
      harborConfig,
      strategy: this.strategy(),
      runningAs: await this.masterUser(),
      listening: await this.listeningPorts()
    }
  }

  /** Validate before reloading — a bad vhost must not take every site down. */
  async test(): Promise<{ ok: boolean; output: string }> {
    const binary = this.native.which('nginx')
    if (!binary) return { ok: false, output: 'nginx is not installed' }
    try {
      const { stderr } = await exec(`${binary} -t`)
      return { ok: true, output: stderr }
    } catch (err) {
      return { ok: false, output: (err as Error).message }
    }
  }

  /**
   * Reload without root when we can: nginx only needs privilege to bind 80/443,
   * and a master started by this user reloads fine as this user. Escalate only
   * if the unprivileged reload is refused.
   */
  async reload(): Promise<void> {
    const check = await this.test()
    if (!check.ok) throw new Error(`nginx config test failed: ${check.output}`)

    // Nothing to reload, and asking for root to signal a process that isn't
    // there would put a password prompt in front of the user for no reason.
    const running = await exec('/usr/bin/pgrep -x nginx')
      .then(() => true)
      .catch(() => false)
    if (!running) return

    const binary = this.native.which('nginx')
    try {
      await exec(`${binary} -s reload`)
    } catch {
      await this.privileged.run(`${binary} -s reload`)
    }
  }

  /**
   * Whether a master is up, cached briefly. describe() asks this for every
   * project on every list, and shelling out to pgrep each time is wasteful.
   */
  async isRunningCached(ttlMs = 3000): Promise<boolean> {
    if (this.runningCache && Date.now() - this.runningCache.at < ttlMs) {
      return this.runningCache.value
    }
    const value = await exec('/usr/bin/pgrep -x nginx')
      .then(() => true)
      .catch(() => false)
    this.runningCache = { value, at: Date.now() }
    return value
  }

  /** What the running master is bound to, which may differ from the config. */
  async listeningPorts(): Promise<number[]> {
    try {
      const { stdout } = await exec(
        "/usr/sbin/lsof -nP -iTCP -sTCP:LISTEN -a -c nginx 2>/dev/null | awk '{print $9}'"
      )
      const ports = new Set<number>()
      for (const line of stdout.split('\n')) {
        const port = Number(line.split(':').pop())
        if (Number.isFinite(port) && port > 0) ports.add(port)
      }
      return [...ports].sort((a, b) => a - b)
    } catch {
      return []
    }
  }

  /** Read back a rendered vhost — used by the UI's "show config" affordance. */
  read(project: Project): string | null {
    const path = this.vhostPath(project)
    return existsSync(path) ? readFileSync(path, 'utf8') : null
  }
}

export const HARBOR_MARKER = '# Added by Harbor'

/**
 * Insert Harbor's include as the first directive inside the top-level `http {}`
 * block. Returns null when it is already present, so callers can treat a
 * repeat connect as a no-op rather than duplicating the line.
 */
export function insertHarborInclude(source: string, includeLine: string): string | null {
  if (source.includes(includeLine)) return null

  const lines = source.split('\n')
  // Match only a top-level `http {`, not a `server {` nested inside one.
  const httpIndex = lines.findIndex((line) => /^\s*http\s*\{/.test(line))
  if (httpIndex === -1) throw new Error('No top-level http { } block found in nginx.conf')

  lines.splice(
    httpIndex + 1,
    0,
    '',
    `    ${HARBOR_MARKER} — serves every .test vhost. Safe to remove.`,
    `    ${includeLine}`
  )
  return lines.join('\n')
}

/**
 * Reverse of insertHarborInclude, exactly: the blank spacer we inserted goes
 * too. A filter that only dropped the marker and include would leave one blank
 * line behind per cycle, slowly accreting in a file Harbor does not own.
 * Returns null when there is nothing to remove.
 */
export function removeHarborInclude(source: string, includeLine: string): string | null {
  if (!source.includes(includeLine)) return null

  const out: string[] = []
  for (const line of source.split('\n')) {
    if (line.includes(HARBOR_MARKER)) {
      // Drop our spacer, but never a blank the user's own config had there.
      if (out[out.length - 1]?.trim() === '') out.pop()
      continue
    }
    if (line.includes(includeLine)) continue
    out.push(line)
  }
  return out.join('\n')
}

function indent(lines: string[], depth = 1): string[] {
  const pad = '    '.repeat(depth)
  return lines.map((l) => (l ? `${pad}${l}` : l))
}
