import { connect } from 'node:net'
import { mkdirSync, writeFileSync, existsSync, rmSync } from 'node:fs'
import { userInfo } from 'node:os'
import { join } from 'node:path'
import type { ProcessManager } from '../core/process-manager.js'
import { paths } from '../core/paths.js'
import type { PhpRuntime } from './php.js'

/**
 * Harbor runs its own PHP-FPM pool per PHP version.
 *
 * The alternative — pointing the vhost at whatever socket Homebrew's own
 * `brew services` php-fpm might be using — was what the first cut did, and it
 * never worked: the path was a guess, nothing created it, and it would have
 * fought the user's own services if it had. Owning the pool means the socket
 * path is a fact rather than a hope, the pool is configured for local dev, and
 * `brew services` is left alone.
 *
 * Pools run through ProcessManager, so their lifecycle and logs behave like
 * every other managed process.
 */
export class PhpFpmManager {
  constructor(
    private readonly php: PhpRuntime,
    private readonly processes: ProcessManager
  ) {}

  private ownerId(version: string): string {
    return `php-fpm-${version}`
  }

  configPath(version: string): string {
    return join(paths.php, version, 'fpm.conf')
  }

  socketPath(version: string): string {
    return this.php.fpmSocket(version)
  }

  /**
   * Whether this pool is usable — not merely whether *this* instance spawned
   * it. Asking only about our own children reported a perfectly healthy pool
   * as down whenever it was started by an earlier run, which then showed as
   * "not served" on a site that serves fine.
   */
  isRunning(version: string): boolean {
    if (this.processes.findByOwner('system', this.ownerId(version)) !== null) return true
    return this.socketAlive(version)
  }

  /**
   * A socket file can outlive the pool that made it, so existence is not
   * enough — try to connect. Local unix sockets make this effectively free.
   */
  private socketAlive(version: string): boolean {
    const socket = this.socketPath(version)
    if (!existsSync(socket)) return false

    const cached = this.aliveCache.get(socket)
    if (cached && Date.now() - cached.at < 3000) return cached.value
    // Kick off a probe for the next caller; report existence meanwhile.
    void this.probeSocket(socket)
    return cached?.value ?? true
  }

  private readonly aliveCache = new Map<string, { value: boolean; at: number }>()

  private probeSocket(socket: string): Promise<boolean> {
    return new Promise((resolve) => {
      const client = connect(socket)
      const settle = (value: boolean): void => {
        this.aliveCache.set(socket, { value, at: Date.now() })
        client.destroy()
        resolve(value)
      }
      client.once('connect', () => settle(true))
      client.once('error', () => settle(false))
      setTimeout(() => settle(false), 500)
    })
  }

  /** Write a pool tuned for local development. */
  writeConfig(version: string): string {
    const dir = join(paths.php, version)
    mkdirSync(dir, { recursive: true })
    mkdirSync(paths.run, { recursive: true })

    const user = userInfo().username
    const socket = this.socketPath(version)
    // FPM ignores user/group unless it is running as root, and logs a NOTICE
    // for each on every start. Harbor's pool always runs as the user, so
    // emitting them only buys log noise.
    const isRoot = process.getuid?.() === 0
    const config = [
      '; Generated by Harbor — do not edit by hand.',
      '[global]',
      `error_log = ${join(paths.logs, `php${version.replace('.', '')}-fpm.log`)}`,
      // ProcessManager owns the lifecycle, so the pool must stay in foreground.
      'daemonize = no',
      '',
      '[harbor]',
      ...(isRoot ? [`user = ${user}`, 'group = staff'] : []),
      `listen = ${socket}`,
      `listen.owner = ${user}`,
      'listen.group = staff',
      // nginx workers run as this same user (Harbor sets nginx's `user`
      // directive), so the pool never needs a world-writable socket.
      'listen.mode = 0660',
      'pm = dynamic',
      // Modest: a laptop running several sites should not spawn 50 workers.
      'pm.max_children = 10',
      'pm.start_servers = 2',
      'pm.min_spare_servers = 1',
      'pm.max_spare_servers = 3',
      'pm.max_requests = 500',
      'catch_workers_output = yes',
      // Surface fatals in the log viewer rather than a blank 500 page.
      'php_admin_value[display_errors] = Off',
      'php_admin_flag[log_errors] = on',
      'request_terminate_timeout = 120',
      ''
    ].join('\n')

    writeFileSync(this.configPath(version), config, 'utf8')
    return this.configPath(version)
  }

  async start(version: string): Promise<void> {
    if (this.isRunning(version)) return

    const binary = this.php.fpmBinary(version)
    if (!binary) {
      throw new Error(
        `PHP ${version} is not installed. Install it with: brew install php@${version}`
      )
    }

    // A socket left behind by a crashed pool stops the new one binding.
    const socket = this.socketPath(version)
    if (existsSync(socket)) rmSync(socket, { force: true })

    const config = this.writeConfig(version)
    await this.processes.spawn({
      owner: { kind: 'system', id: this.ownerId(version) },
      label: `php-fpm ${version}`,
      command: binary,
      // -F keeps it in the foreground; -y points at our pool, not the system's.
      args: ['-F', '-y', config]
    })

    if (!(await this.waitForSocket(version))) {
      throw new Error(`php-fpm ${version} started but never created ${socket}`)
    }
  }

  /** A spawned pool is not a listening one; the vhost needs the socket to exist. */
  private async waitForSocket(version: string, timeoutMs = 5000): Promise<boolean> {
    const socket = this.socketPath(version)
    const deadline = Date.now() + timeoutMs
    while (Date.now() < deadline) {
      if (existsSync(socket)) return true
      await new Promise((r) => setTimeout(r, 100))
    }
    return false
  }

  async stop(version: string): Promise<void> {
    const handle = this.processes.findByOwner('system', this.ownerId(version))
    if (handle) await this.processes.stop(handle.id)
    rmSync(this.socketPath(version), { force: true })
  }

  async stopAll(): Promise<void> {
    for (const handle of this.processes.list()) {
      if (handle.owner.kind === 'system' && handle.owner.id.startsWith('php-fpm-')) {
        await this.processes.stop(handle.id)
      }
    }
  }

  /** Versions with a running pool, for status display. */
  running(): string[] {
    return this.processes
      .list()
      .filter((h) => h.owner.kind === 'system' && h.owner.id.startsWith('php-fpm-') && h.pid)
      .map((h) => h.owner.id.replace('php-fpm-', ''))
  }
}
